#!/bin/bash
echo "*********************************************************"
echo "Running git pre-push hook. Running Test Cases ... "
echo "*********************************************************"

# Function to find the project root directory by looking for the presence of settings.gradle or settings.gradle.kts
find_project_root() {
  local dir="$1"
  while [[ "$dir" != "/" && ! -f "$dir/settings.gradle" && ! -f "$dir/settings.gradle.kts" ]]; do
    dir=$(dirname "$dir")
  done
  if [[ -f "$dir/settings.gradle" || -f "$dir/settings.gradle.kts" ]]; then
    echo "$dir"
  else
    echo ""
  fi
}

# Get the current working directory
BASE_DIR="$(pwd)"

# Find the project root directory
PROJECT_ROOT=$(find_project_root "$BASE_DIR")
if [[ -z "$PROJECT_ROOT" ]]; then
  echo "Error: Could not find the project root directory."
  exit 1
fi

echo "Debug: Project root directory - $PROJECT_ROOT"

# Find all module directories containing src/test/java or src/test/kotlin
MODULE_TEST_DIRS=$(find "$PROJECT_ROOT" -type d \( -path "*/src/test/java" -o -path "*/src/test/kotlin" \))

# Initialize variable to store the directory containing the subclass
TARGET_DIR=""

# Search for class KonsistLintingTest in the test directories of all modules
while IFS= read -r dir; do
  if grep -qrE "KonsistLintingTest" "$dir"; then
    TARGET_DIR="$dir"
    break
  fi
done <<< "$MODULE_TEST_DIRS"

if [ -n "$TARGET_DIR" ]; then
  echo "Class KonsistLintingTest found in directory: $TARGET_DIR"
  echo "Running unit tests..."

  # Change to the main project directory to be able to run ./gradlew
  cd "$PROJECT_ROOT" || { echo "Warning: Could not change to directory $PROJECT_ROOT. Proceeding with current directory."; }

  TEST_COMMAND="./gradlew testDebugUnitTest"

  # Run the appropriate gradlew command
  $TEST_COMMAND

  status=$?

  echo "Unit Test Result => $status"

  if [ "$status" -eq 0 ] ; then
    echo "*********************************************************"
    echo "All test cases passed."
    echo "*********************************************************"
    # Exit
    exit 0
  else
    echo "*********************************************************"
    echo "Some test cases failed"
    echo "*********************************************************"
    # Exit
    exit 1
  fi
else
  echo "*********************************************************"
  echo "Class KonsistLintingTest not found...."
  echo "*********************************************************"
  # Exit
  exit 1
fi